name: Build Tauri App

on:
    workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfuse2 \
            libglib2.0-dev \
            libgtk-3-dev \
            libjavascriptcoregtk-4.1-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            libwebkit2gtk-4.1-dev \
            pkg-config
          sudo apt install --reinstall ca-certificates
          sudo update-ca-certificates -f

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install npm dependencies
        run: npm install

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri app for Linux
        if: matrix.os == 'ubuntu-latest'
        run: cargo tauri build --verbose --bundles appimage
          
      - name: Build Tauri app for macOS
        if: matrix.os == 'macos-latest'
        run: cargo tauri build --bundles dmg

      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-dmg
          path: src-tauri/target/release/bundle/dmg

      - name: Upload Linux artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-appimage
          path: src-tauri/target/release/bundle/appimage