name: Build Tauri App (MacOS)

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: "macos-latest"
    # env:
    #   TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install npm dependencies
        run: npm install

      - name: Run Tauri
        uses: tauri-apps/tauri-action@v0
        with:
          updaterJsonPreferNsis: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-dmg
          path: src-tauri/target/release/bundle/dmg