name: Build Tauri App (Linux)

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    # env:
    #   TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfuse2 \
            libglib2.0-dev \
            libgtk-3-dev \
            libjavascriptcoregtk-4.1-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            libwebkit2gtk-4.1-dev \
            pkg-config
          sudo apt install --reinstall ca-certificates
          sudo update-ca-certificates -f

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install npm dependencies
        run: npm install

      - name: Run Tauri
        uses: tauri-apps/tauri-action@v0
        with:
          updaterJsonPreferNsis: true

      # - name: Install Tauri CLI
      #   run: cargo install tauri-cli

      # - name: Build Tauri app for Linux
      #   run: cargo tauri build --verbose --bundles appimage
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-appimage
          path: src-tauri/target/release/bundle/appimage